language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - npm install -g now
install:
  - yarn install
script:
  - yarn eslint src
  - yarn build
deploy:  
  - provider: script
    skip_cleanup: true
    script: chmod +x .travis/deploy-now.sh && .travis/deploy-now.sh
    on:
      branch:
        - master
        - feat/travis